---
- name: Enable systemd service
  systemd:
    name: clickhouse-server.service
    enabled: yes
  register: enable_service
  # Ignore non-existing service error in check mode
  failed_when: enable_service.failed and (not ansible_check_mode or not enable_service.msg.startswith("Could not find the requested service"))
  changed_when: enable_service.changed or enable_service.failed

- name: Debug start systemd service
  systemd:
    name: clickhouse-server.service
    enabled: yes
  register: enable_service
  # Ignore non-existing service error in check mode
  failed_when: enable_service.failed and (not ansible_check_mode or not enable_service.msg.startswith("Could not find the requested service"))
  changed_when: enable_service.changed or enable_service.failed

- name: Debug Restart clickhouse-server
  service:
    name: clickhouse-server
    state: restarted
  register: debug_restart_result
  ignore_errors: true

- name: Debug restart output
  debug:
    var: debug_restart_result.stderr_lines

- name: Get journalctl logs
  command: journalctl -xeu clickhouse-server
  register: debug_clickhouse_journal
  ignore_errors: true

- name: Debug restart output
  debug:
    var: debug_clickhouse_journal.stdout_lines

- name: Get CH logs
  command: tail -100 /var/log/clickhouse-server/clickhouse-server.err.log
  register: debug_ch_logs
  ignore_errors: true

- name: Debug restart output
  debug:
    var: debug_ch_logs.stdout_lines

- name: Get CH logs
  command: "getent ahosts ::"
  register: debug_ahosts
  ignore_errors: true

- name: Debug restart output
  debug:
    var: debug_ahosts.stdout_lines

- name: Get /etc/hosts
  shell: |
    echo "# /etc/hosts"
    cat /etc/hosts
    echo "# disable ipv6"
    cat /proc/sys/net/ipv6/conf/all/disable_ipv6
  register: debug_hosts
  ignore_errors: true

- name: Debug restart output
  debug:
    var: debug_hosts.stdout_lines


- name: Notify handlers manually
  meta: flush_handlers

# NOTE: that since 23.1 ther is systemd notify support, so this does not make a
# lot of sense, but let's keep it, since sometimes server may notify, but may
# not be available by TCP.
- name: Wait for clickhouse-server
  wait_for:
    # NOTE: This is tcp_port, but we can move this into vars/config.yml
    port: 9000
    delay: 1
    connect_timeout: 1
    # we have pretty tiny setup, it should start fast.
    timeout: 30
  when: (clickhouse_restarted is defined and clickhouse_restarted.changed) or (clickhouse_started is defined and clickhouse_started.changed)
