---
- name: Collect config file stats
  stat:
    path: "{{ item }}"
  register: __config_exists__

- name: Assert config file not exists
  assert:
    that: "{{ not __config_exists__.stat.exists }}"
    fail_msg: "Configuration file {{ item }} exists"
